---
- hosts: localhost
  connection: local
  vars_files:
    - /etc/stereum/ethereum2.yaml

  tasks:
    - name: exit validator account
      include_role:
        name: exit-validator-keys-lighthouse
      when: setup == "lighthouse"

    - name: exit validator account
      include_role:
        name: exit-validator-keys-lodestar
      when: setup == "lodestar" 
    
    - name: exit validator account
      include_role:
        name: exit-validator-keys-prysm
      when: setup == "prysm"  
