---
- hosts: localhost
  connection: local
  vars_files:
    - /etc/stereum/ethereum2.yaml

  roles:
    - role: switch-to-network
    - role: set-setup
    - role: set-public-ip
    - role: set-override
    - role: set-external-eth1

    - role: start-services

# EOF
