---
- hosts: localhost
  connection: local
  vars_files:
    - /etc/stereum/ethereum2.yaml

  roles:
    - role: add-stereum-user
    - role: configure-timesyncd
    - role: install-docker
    - role: install-e2dc
      install_e2dc_install_path: "{{ e2dc_install_path }}"
    - role: install-e2a
    - role: install-e2ccc
    - role: switch-to-network
    - role: set-setup
    - role: set-public-ip
    - role: set-override
    - role: set-external-eth1
    - role: start-services
    - role: install-ansible
      start-services: "{{ setups[setup] }}"
