---test
- hosts: localhost
  connection: local
  vars_files:
  - ./vars/vars.yaml

  roles:
    - role: add-stereum-user
    - role: configure-timesyncd
    - role: install-docker
    - role: install-e2dc
    - role: switch-to-network
    - role: set-setup
    - role: set-public-ip
    - role: start-services
      start-services: "{{ setups[setup] }}"
