---
- hosts: localhost
  connection: local
  vars_files:
    - /etc/stereum/ethereum2.yaml

  roles:
    - role: stop-services
      stop-services: "{{ setups[setup].services }}"

    - role: git-checkout-tag
      git_checkout_tag_git_repo_path: "{{ e2a_install_path }}"
      git_update_pull_tag: "{{ stereum_version_tag }}"
      skip_stashing: true

    - role: git-checkout-tag
      git_checkout_tag_git_repo_path: "{{ e2ccc_install_path }}"
      git_update_pull_tag: "{{ stereum_version_tag }}"
      skip_stashing: true

    - role: git-checkout-tag
        git_checkout_tag_git_repo_path: "{{ e2dc_install_path }}"
        git_update_pull_tag: "{{ stereum_version_tag }}"
        skip_stashing: false