---
- name: stash changes
  shell: git stash save "changes"
  args:
    chdir: "{{ git_update_pull_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"

- name: pull latest changes
  shell: git pull 
  args:
    chdir: "{{ git_update_pull_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"

- name: put the changes back to the repository
  shell: git stash pop
  args:
    chdir: "{{ git_update_pull_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"
