--
- name: Start services
  command: "docker-compose --compatibility up -d {{ start-services.services | join(' ') }}"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"
