---
- name: Test for prater network branch mapping
  shell: grep -c "^\s{2}prater" /etc/stereum/ethereum2.yaml || true
  register: grep_prater_mapping
  become: yes

- name: Add prater network branch mapping to config
  lineinfile:
    dest: "/etc/stereum/ethereum2.yaml"
    insertafter: "^networks:"
    line: "  prater: prater"
  when: grep_prater_mapping.stdout == "0"
  become: yes

- name: Test for exit-account
  shell: grep -c "^\s{4}exit_account:\slighthouse-only" /etc/stereum/ethereum2.yaml || true
  register: exit_account
  become: yes

- name: Add exit-account to config
  lineinfile:
    dest: "/etc/stereum/ethereum2.yaml"
    insertafter: '^\s{4}create_account:\slighthouse-only\/create-account\.yaml'
    line: "    exit_account: lighthouse-only/exit-account.yaml"
  when: exit_account.stdout == "0"
  become: yes

- name: Test for teku overrides
  shell: grep -c "^\s{4}overrides_path:\scompose-examples\/teku-only\/override-examples" /etc/stereum/ethereum2.yaml || true
  register: grep_teku_no_geth
  become: yes

- name: Add teku overrides to config
  lineinfile:
    dest: "/etc/stereum/ethereum2.yaml"
    insertafter: '^\s{4}compose_path:\steku-only'
    line: "    overrides_path: compose-examples/teku-only/override-examples"
  when: grep_teku_no_geth.stdout == "0"
  become: yes

- name: Remove override config
  replace:
    dest: "/etc/stereum/ethereum2.yaml"
    regexp: '^\s{4}overrides:(\n\s{6}.*)*'
    replace: ""
  become: yes

# EOF
