---
- name: Install expect
  apt:
    name: expect    

- name: Copy lanchpad wallet's validator_keys
  command: "cp -r {{ validator_keys_path }}/. {{ e2dc_install_path }}/launchpad"
  become: yes
  become_user: "{{ stereum_user }}"
  when: setups[setup].create_account is defined 

- name: Run import
  script: "{{ e2dc_install_path }}/import.sh"
  args:
    chdir: "{{ e2dc_install_path }}"
  register: result 
  become: yes
  become_user: "{{ stereum_user }}"
  ignore_errors: yes
  when: setups[setup].create_account is defined  

- name: Error massage
  fail:
    msg: "Invalid Password!!! Please check your validator password and try it again."       
  failed_when: "'Invalid password' in result.stdout" 
