---
- name: Get cpu information
  shell: grep -c "adx" /proc/cpuinfo || true
  register: grep_adx_cpu_info
  when: setup == "lighthouse"
  become: yes

- name: Switch to slower portable lighthouse
  replace:
    path: "{{ e2dc_install_path }}/.env"
    regexp: '(LIGHTHOUSE_DOCKER_TAG=v[\d\.]*)(.*)'
    replace: '\1-portable\3'
  when: setup == "lighthouse" and grep_adx_cpu_info.stdout == "0"
  become: yes

# EOF
