---
- name: Install pip
  apt:
    update_cache: yes
    name:
      - python3-pip

- name: Install pexpect
  pip:
    name: pexpect

- name: Set correct permissions
  shell: "chmod -R 700 {{ e2dc_install_path }}/data/validator"

- name: Run import
  ansible.builtin.expect:
    command: "docker-compose -f create-account.yaml run validator-import-launchpad"
    responses:
      (?i)password: "{{ validator_password }}"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"

# EOF
