---
- name: stash changes
  shell: git stash save "changes"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes  

- name: fetch latest changes
  shell: git fetch
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  
- name: merge latest changes into local repository
  shell: git merge
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes

- name: put the changes back to the repository 
  shell: git stash pop
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes  
